### ISSUE TITLE
python3 issue to save files

### ISSUE THREAD

**Issue by jegarfa** [hchauvet/beampy#10]
Hi!!, I'm trying to use beampy in python3 (because the latest version of bokeh is not completely compatible with python2), and apparently there is an issue related to save the outputs. The follow is the result after run the simple example. Thanks!. btw its a great project!

`-----------------------------------------------------------------------------

  File "simple_one.py", line 25, in <module>
    save('./simple_one.html')
  File "/home/garfa/Documents/beampy-src/python3/src/beampy/beampy/exports.py", line 47, in save
    render_texts()
  File "/home/garfa/Documents/beampy-src/python3/src/beampy/beampy/functions.py", line 671, in render_texts
    schema = allsvgs[0]
IndexError: list index out of range

-----------------------------------------------------------------------------`

**Comment by hchauvet** [comment]
Hi, thx for reporting the issue. Beampy is not yet ready for python3. I'm currently working other issue for beampy. After, I will work on a python3 version of Beampy.
