### ISSUE TITLE
Inkscape breaks due to equal sign after short option

### ISSUE THREAD

**Issue by vonopr** [hchauvet/beampy#32]
There is an equal sign (=) between short flag option *-d* of *inkscape* shell command and its value. 

A new v1.2 version of  *inkscape*  does not allow that. I guess we can just remove the equal sing wihtout loss of compatibility with inkscape's older versions. Though I didn't check that.

**Comment by hchauvet** [comment]
Hi,

Thanks for the bug fix, I will check if it works with lower version and merge your modifications.
